routes/web.php
<?php

use App\Http\Controllers\AnniversaryTypeController;
use App\Http\Controllers\Central\AccountController;
use App\Http\Controllers\Central\AccountElementController;
use App\Http\Controllers\Central\AccountTypeController;
use App\Http\Controllers\Central\AssessmentMasterController;
use App\Http\Controllers\Central\AssessmentMasterDetailsController;
use App\Http\Controllers\Central\AssetClassController;
use App\Http\Controllers\Central\AssignmentStandardCostController;
use App\Http\Controllers\Central\BusinessFunctionController;
use App\Http\Controllers\Central\ContractTypeController;
use App\Http\Controllers\Central\CostCenterController;
use App\Http\Controllers\Central\CountryController;
use App\Http\Controllers\Central\CvCompanyController;
use App\Http\Controllers\Central\DashboardComponentController;
use App\Http\Controllers\Central\DefaultDashboardController;
use App\Http\Controllers\Central\DefaultFavouriteController;
use App\Http\Controllers\Central\DeliveryTypeController;
use App\Http\Controllers\Central\ExpenseTypeController;
use App\Http\Controllers\Central\FavouriteController;
use App\Http\Controllers\Central\IndustryController;
use App\Http\Controllers\Central\InvoiceStatusController;
use App\Http\Controllers\Central\LeaveTypeController;
use App\Http\Controllers\Central\MaritalStatusController;
use App\Http\Controllers\Central\MedicalCertificateTypeController;
use App\Http\Controllers\Central\OnboardingStatusController;
use App\Http\Controllers\Central\PaymentBaseController;
use App\Http\Controllers\Central\PaymentMethodController;
use App\Http\Controllers\Central\PaymentTermController;
use App\Http\Controllers\Central\PaymentTypeController;
use App\Http\Controllers\Central\ProcessInterviewController;
use App\Http\Controllers\Central\ProcessStatusController;
use App\Http\Controllers\Central\ProfessionController;
use App\Http\Controllers\Central\ProjectStatusController;
use App\Http\Controllers\Central\ProjectTermController;
use App\Http\Controllers\Central\ProjectTypeController;
use App\Http\Controllers\Central\ProspectStatusController;
use App\Http\Controllers\Central\QuotationTermController;
use App\Http\Controllers\Central\RelationshipController;
use App\Http\Controllers\Central\ResourceLevelController;
use App\Http\Controllers\Central\ResourcePositionController;
use App\Http\Controllers\Central\ScoutingRoleController;
use App\Http\Controllers\Central\SkillLevelController;
use App\Http\Controllers\Central\SolutionController;
use App\Http\Controllers\Central\SpecialityController;
use App\Http\Controllers\Central\SprintStatusController;
use App\Http\Controllers\Central\StatusController;
use App\Http\Controllers\Central\SystemController;
use App\Http\Controllers\Central\SystemHealthController;
use App\Http\Controllers\Central\TemplateStyleController;
use App\Http\Controllers\Central\TemplateTypeController;
use App\Http\Controllers\Central\TermController;
use App\Http\Controllers\Central\TitleController;
use App\Http\Controllers\Central\UserController;
use App\Http\Controllers\Central\UserTypeController;
use App\Http\Controllers\Central\VatRateController;
use App\Http\Controllers\Central\VendorInvoiceStatusController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', fn() => "<div style='font-family:arial;font-size: 24px;margin: 25px;display:flex;justify-content:center;
  align-items: center;height:100dvh'>
  <div class='child'><h2>No body is home at the moment...</h2></div>
</div>");

Route::prefix('admin')->name('admin.')->group(function () {
    Route::get('/login', [UserController::class, 'login']);
    Route::post('/auth', [UserController::class, 'adminLogin'])->name('login');

   Route::middleware('auth')->group(function (){
        Route::get('/', fn() => "Logged in!");
        Route::resource('/account', AccountController::class);
        Route::resource('/accounttype', AccountTypeController::class);
        Route::resource('/accountelement', AccountElementController::class);
        Route::resource('/assessmentmaster', AssessmentMasterController::class);
        Route::resource('/assessmentmasterdetails', AssessmentMasterDetailsController::class);
        Route::resource('/anniversarytype', AnniversaryTypeController::class);
        Route::resource('/assetclass', AssetClassController::class);
        Route::resource('assignmentstandardcost', AssignmentStandardCostController::class);
        Route::resource('/businessfunction', BusinessFunctionController::class);
        Route::resource('/costcenter', CostCenterController::class);
        Route::resource('/contracttype', ContractTypeController::class);
        Route::resource('/country', CountryController::class);
        Route::resource('/cvcompany', CvCompanyController::class);
        Route::resource('/customisedashboard', DashboardComponentController::class);
        Route::resource('/dashboard', DefaultDashboardController::class);
        Route::resource('/defaultfavs', DefaultFavouriteController::class);
        Route::resource('/expensetype', ExpenseTypeController::class);
        Route::resource('/deliverytype', DeliveryTypeController::class);
        Route::resource('/favourites', FavouriteController::class);
        Route::resource('/industry', IndustryController::class);
        Route::resource('/profession', ProfessionController::class);
        Route::resource('/speciality', SpecialityController::class);
        Route::resource('/sprintstatus', SprintStatusController::class);
        Route::resource('/leavetype', LeaveTypeController::class);
        Route::resource('/maritalstatus', MaritalStatusController::class);
        Route::resource('/medical', MedicalCertificateTypeController::class);
        Route::resource('/paymentbase', PaymentBaseController::class);
        Route::resource('/paymenttype', PaymentTypeController::class);
        Route::resource('/processinterview', ProcessInterviewController::class);
        Route::resource('/processstatus', ProcessStatusController::class);
        Route::resource('/prospectstatus', ProspectStatusController::class);
        Route::resource('/projectterms', ProjectTermController::class);
        Route::resource('/quotationterms', QuotationTermController::class);
        Route::resource('/relationship', RelationshipController::class);
        Route::resource('/resourcelevel', ResourceLevelController::class);
        Route::resource('/resourceposition', ResourcePositionController::class);
        Route::resource('/skilllevel', SkillLevelController::class);
        Route::resource('/solution', SolutionController::class);
        Route::resource('/skill', SystemController::class);
        Route::resource('/onboardingstatus', OnboardingStatusController::class);
        Route::resource('/title', TitleController::class);
        Route::resource('/templatestyles', TemplateStyleController::class);
        Route::resource('/scoutingrole', ScoutingRoleController::class);
        Route::resource('/usertype', UserTypeController::class);
        Route::resource('/vatrate', VatRateController::class);
        Route::resource('/invoicestatus', InvoiceStatusController::class);
        Route::resource('/paymentmethod', PaymentMethodController::class);
        Route::resource('/paymentterms', PaymentTermController::class);
        Route::resource('/projecttype', ProjectTypeController::class);
        Route::resource('/projectstatus', ProjectStatusController::class);
        Route::resource('/status', StatusController::class);
        Route::resource('/systemhealth', SystemHealthController::class);
        Route::resource('/term', TermController::class);
        Route::resource('/vendorinvoicestatus', VendorInvoiceStatusController::class);
        Route::resource('/template', TemplateTypeController::class);
    });
});

Route::webhooks('generate-tenant');

app/Models/Central/Profession.php
<?php

namespace App\Models\Central;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Profession extends Model
{
    use HasFactory, SoftDeletes;

    public function creator()
    {
        return $this->belongsTo(User::class, 'creator_id');
    }

    public function status()
    {
        return $this->belongsTo(Status::class, 'status_id');
    }
}

app/Http/Controllers/Central/ProfessionController.php
<?php

namespace App\Http\Controllers\Central;

use App\Http\Controllers\Controller;
use App\Http\Requests\ProfessionRequest;
use App\Models\Central\Profession;
use App\Models\Central\Status;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

class ProfessionController extends Controller
{
    public function index(Request $request): View
    {
        $item = $request->input('s') ?? 15;

        $professions = Profession::where('status_id', 1);

        if ($request->has('status_filter') && $request->input('status_filter') != '') {
            if ($request->input('status_filter') != 0) {
                $professions = Profession::where('status_id', $request->input('status_filter'));
            }else{
                $professions = Profession::query();
            }
        }

        if ($request->has('q') && $request->input('q') != '') {
            $professions = $professions->where('name', 'like', '%'.$request->input('q').'%');
        }

        $professions = $professions->paginate($item);

        $parameters = [
            'professions' => $professions,
        ];

        return view('admin.profession.index')->with($parameters);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create(): View
    {
        $autocomplete_elements = Profession::orderBy('name')->where('name', '!=', null)->where('name', '!=', '')->get();
        $status_drop_down = Status::orderBy('id')->orderBy('order')->where('status', '=', 1)->pluck('description', 'id')->prepend('Status', '0');

        $parameters = [
            'autocomplete_elements' => $autocomplete_elements,
            'status_drop_down' => $status_drop_down,
        ];

        return view('admin.profession.create')->with($parameters);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(ProfessionRequest $request): RedirectResponse
    {
        $profession = new Profession();
        $profession->name = $request->input('name');
        $profession->creator_id = Auth()->id();
        $profession->status_id = $request->input('status_id');
        $profession->save();

        return redirect(route('admin.profession.index'))->with('flash_success', 'Profession saved successfully.');
    }

    /**
     * Display the specified resource.
     */
    public function show(Profession $profession): View
    {
        $profession = Profession::find($profession->id);
        $status_drop_down = Status::orderBy('id')->orderBy('order')->where('status', '=', 1)->pluck('description', 'id')->prepend('Status', '0');

        $parameters = [
            'profession' => $profession,
            'status_drop_down' => $status_drop_down,
        ];

        return view('admin.profession.show')->with($parameters);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Profession $profession): View
    {
        $autocomplete_elements = Profession::orderBy('name')->where('name', '!=', null)->where('name', '!=', '')->get();
        $status_drop_down = Status::orderBy('id')->orderBy('order')->where('status', '=', 1)->pluck('description', 'id')->prepend('Status', '0');

        $profession = Profession::find($profession->id);

        $parameters = [
            'profession' => $profession,
            'autocomplete_elements' => $autocomplete_elements,
            'status_drop_down' => $status_drop_down,
        ];

        return view('admin.profession.edit')->with($parameters);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(ProfessionRequest $request, Profession $profession): RedirectResponse
    {
        $profession = Profession::find($profession->id);
        $profession->name = $request->input('name');
        $profession->creator_id = Auth()->id();
        $profession->status_id = $request->input('status_id');
        $profession->save();

        return redirect(route('admin.profession.index'))->with('flash_success', 'Profession updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy( $profession): RedirectResponse
    {
        $item = Profession::find($profession);
        $item->status_id = 2;
        $item->save();

        return redirect(route('admin.profession.index'))->with('flash_success', 'Profession suspended successfully.');
    }
}

app/Http/Controllers/ProfessionController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProfessionRequest;
use App\Models\Profession;
use App\Models\Status;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

class ProfessionController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     */
    public function index(Request $request): View
    {
        // $professions = Profession::orderBy('id');

        $item = $request->input('s') ?? 15;

        $professions = Profession::with(['status:id,description'])->sortable('name', 'asc')->where('status_id', 1);

        if ($request->has('status_filter') && $request->input('status_filter') != '') {
            if ($request->input('status_filter') != 0) {
                $professions = $professions->where('status_id', $request->input('status_filter'));
            }else{
                $professions = $professions->sortable('name', 'asc');
            }
        }

        if ($request->has('q') && $request->input('q') != '') {
            $professions = $professions->where('name', 'like', '%'.$request->input('q').'%');
        }

        $professions = $professions->paginate($item);

        $parameters = [
            'professions' => $professions,
        ];

        return view('master_data.profession.index')->with($parameters);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create(): View
    {
        $autocomplete_elements = Profession::orderBy('name')->where('name', '!=', null)->where('name', '!=', '')->get();
        $status_drop_down = Status::orderBy('id')->orderBy('order')->where('status', '=', 1)->pluck('description', 'id')->prepend('Status', '0');

        $parameters = [
            'autocomplete_elements' => $autocomplete_elements,
            'status_drop_down' => $status_drop_down,
        ];

        return view('master_data.profession.create')->with($parameters);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(ProfessionRequest $request): RedirectResponse
    {
        $profession = new Profession();
        $profession->name = $request->input('name');
        $profession->creator_id = Auth()->id();
        $profession->status_id = $request->input('status_id');
        $profession->save();

        return redirect(route('profession.index'))->with('flash_success', 'Profession saved successfully.');
    }

    /**
     * Display the specified resource.
     */
    public function show(Profession $profession): View
    {
        $profession = Profession::find($profession->id);
        $status_drop_down = Status::orderBy('id')->orderBy('order')->where('status', '=', 1)->pluck('description', 'id')->prepend('Status', '0');

        $parameters = [
            'profession' => $profession,
            'status_drop_down' => $status_drop_down,
        ];

        return view('master_data.profession.show')->with($parameters);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Profession $profession): View
    {
        $autocomplete_elements = Profession::orderBy('name')->where('name', '!=', null)->where('name', '!=', '')->get();
        $status_drop_down = Status::orderBy('id')->orderBy('order')->where('status', '=', 1)->pluck('description', 'id')->prepend('Status', '0');

        $profession = Profession::find($profession->id);

        $parameters = [
            'profession' => $profession,
            'autocomplete_elements' => $autocomplete_elements,
            'status_drop_down' => $status_drop_down,
        ];

        return view('master_data.profession.edit')->with($parameters);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(ProfessionRequest $request, Profession $profession): RedirectResponse
    {
        $profession = Profession::find($profession->id);
        $profession->name = $request->input('name');
        $profession->creator_id = Auth()->id();
        $profession->status_id = $request->input('status_id');
        $profession->save();

        return redirect(route('profession.index'))->with('flash_success', 'Profession updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy( $profession): RedirectResponse
    {
        // Profession::destroy($profession->id);
        $item = Profession::find($profession);
        $item->status_id = 2;
        $item->save();

        return redirect(route('profession.index'))->with('flash_success', 'Profession suspended successfully.');
    }
}

resources/views/admin/profession/create.blade.php
@extends('admin.adminlte.default')

@section('title') Add Master Data Profession @endsection

@section('header')
    <div class="container-fluid container-title">
        <h3>@yield('title')</h3>
        <div class="btn-toolbar float-right">
            <button onclick="history.back()" class="btn btn-dark float-right" style="margin-top: -7px;"><i class="fa fa-caret-left"></i> Back</button>
            <a href="javascript:void(0)" onclick="saveForm('saveForm')" class="btn btn-primary ml-1" style="margin-top: -7px;">Save</a>
        </div>
    </div>
@endsection

@section('content')
    <div class="container-fluid">
        <hr />
        <div class="table-responsive">
            {{Form::open(['url' => route('admin.profession.store'), 'method' => 'post','class'=>'mt-3','files'=>true,'id'=>'saveForm'])}}
            <table class="table table-bordered table-sm">
                <tbody>
                    <tr>
                        <th>Name:</th>
                        <td>
                            {{Form::text('name', old('name'), ['class'=>'form-control form-control-sm'. ($errors->has('name') ? ' is-invalid' : ''), 'id' => 'name', 'autocomplete' => 'off'])}}
                            @foreach($errors->get('name') as $error)
                                <div class="invalid-feedback">
                                    {{$error}}
                                </div>
                            @endforeach
                        </td>
                    </tr>
                    <tr>
                        <th>Status:</th>
                        <td>
                            {{Form::select('status_id', $status_drop_down, 1, ['class'=>'form-control form-control-sm ','id'=>'status_id'])}}
                            @foreach($errors->get('status_id') as $error)
                                <div class="invalid-feedback">
                                    {{$error}}
                                </div>
                            @endforeach
                        </td>
                    </tr>
                </tbody>
            </table>
            {{Form::close()}}
        </div>
    </div>
@endsection
@section('extra-css')
    <style>
        .ui-menu .ui-menu-item {
            position: relative;
            margin: 0;
            padding: 3px 1em 3px .4em;
            cursor: pointer;
            min-height: 0;
            font-size: 13px;
            list-style-image: url(data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7);
        }
    </style>
@endsection
@section('extra-js')
    <script>
        $(function () {
            let autocomplete_elements = [@foreach($autocomplete_elements as $autocomplete_element) {!! '"'.$autocomplete_element->name.'",' !!} @endforeach];

            $( "#name" ).autocomplete({
                source: autocomplete_elements
            });
        });
    </script>
@endsection

resources/views/admin/profession/edit.blade.php
@extends('admin.adminlte.default')

@section('title') Edit Master Data Profession @endsection

@section('header')
    <div class="container-fluid container-title">
        <h3>@yield('title')</h3>
        <div class="btn-toolbar float-right">
            <button onclick="history.back()" class="btn btn-dark float-right" style="margin-top: -7px;"><i class="fa fa-caret-left"></i> Back</button>
            <a href="javascript:void(0)" onclick="saveForm('saveForm')" class="btn btn-primary ml-1" style="margin-top: -7px;">Save</a>
        </div>
    </div>
@endsection

@section('content')
    <div class="container-fluid">
        <hr />
        <div class="table-responsive">
            {{Form::open(['url' => route('admin.profession.update', $profession), 'method' => 'patch','class'=>'mt-3','files'=>true,'id'=>'saveForm'])}}
            <table class="table table-bordered table-sm">
                <tbody>
                <tr>
                    <th>Name:</th>
                    <td>
                        {{Form::text('name', $profession->name, ['class'=>'form-control form-control-sm'. ($errors->has('name') ? ' is-invalid' : ''), 'id' => 'name', 'autocomplete' => 'off'])}}
                        @foreach($errors->get('industry') as $error)
                            <div class="invalid-feedback">
                                {{$error}}
                            </div>
                        @endforeach
                    </td>
                </tr>
                <tr>
                    <th>Status:</th>
                    <td>
                        {{Form::select('status_id', $status_drop_down, $profession->status_id, ['class'=>'form-control form-control-sm ','id'=>'status_id'])}}
                        @foreach($errors->get('status_id') as $error)
                            <div class="invalid-feedback">
                                {{$error}}
                            </div>
                        @endforeach
                    </td>
                </tr>
                </tbody>
            </table>
            {{Form::close()}}
        </div>
    </div>
@endsection
@section('extra-css')
    <style>
        .ui-menu .ui-menu-item {
            position: relative;
            margin: 0;
            padding: 3px 1em 3px .4em;
            cursor: pointer;
            min-height: 0;
            font-size: 13px;
            list-style-image: url(data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7);
        }
    </style>
@endsection
@section('extra-js')
    <script>
        $(function () {
            let autocomplete_elements = [@foreach($autocomplete_elements as $autocomplete_element) {!! '"'.$autocomplete_element->name.'",' !!} @endforeach];

            $( "#name" ).autocomplete({
                source: autocomplete_elements
            });
        });
    </script>
@endsection

resources/views/admin/profession/index.blade.php
@extends('admin.adminlte.default')

@section('title') Master Data - Profession @endsection

@section('header')
    <div class="container-fluid container-title">
        <h3>@yield('title')</h3>
        <a href="{{route('admin.profession.create')}}" class="btn btn-dark float-right"><i class="fa fa-plus"></i> Profession</a>
    </div>
@endsection

@section('content')
    <div class="container-fluid">
        <form id="searchform" class="form-inline mt-3" method="get" autocomplete="off">
            <div class="col-sm-3 col-sm mt-3">
                <div class="form-group input-group">
                    <label class="has-float-label">
                        <input type="text" name="q" class="form-control w-100" value="{{isset($_GET['q']) ? $_GET['q'] : ''}}" onkeyup="handle(event)" />
                        <span>Matching</span>
                    </label>
                </div>
            </div>
            <div class="col-sm-3 col-sm mt-3">
                <div class="form-group input-group">
                    <label class="has-float-label">
                        <select class="form-control" name="status_filter" id="status_filter" style="width: 120px;">
                            <option value="0">All</option>
                            <option selected value="1">Active</option>
                            <option value="2">Suspended</option>
                            <option value="6">Closed</option>
                        </select>
                        <span>Status</span>
                    </label>
                </div>
            </div>
            <div class="col-sm-3 col-sm mt-2">
                <a href="{{ route('admin.profession.index') }}" class="btn btn-info w-100">Clear Filters</a>
            </div>
        </form>

        <hr>
        <div class="table-responsive">
            <table class="table table-bordered table-sm table-hover">
                <thead>
                <tr class="btn-dark">
                    <th>@sortablelink('description','Description')</th>
                    <th>Status</th>
                    <th class="text-right last">Action</th>
                </tr>
                </thead>
                <tbody>
                @forelse($professions as $profession)
                    <tr>
                        <td><a href="{{route('admin.profession.show',$profession)}}">{{$profession->name}}</a></td>
                        <td>{{$profession->status?->description}}</td>
                        <td class="text-right">
                            <div class="d-flex">
                            <a href="{{route('admin.profession.edit',$profession)}}" class="btn btn-success btn-sm mr-1"><i class="fas fa-pencil-alt"></i></a>
                            {{ Form::open(['method' => 'DELETE','route' => ['admin.profession.destroy', $profession],'style'=>'display:inline','class'=>'delete']) }}
                            <button type="submit" class="btn btn-danger btn-sm"><i class="fas fa-trash"></i></button>
                            {{ Form::close() }}
                            </div>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="100%" class="text-center">No master data profession entries match those criteria.</td>
                    </tr>
                @endforelse
                </tbody>
            </table>
            <div class="w-100 d-block col-md-12 text-center" style="align-items: center;">      
                <table class="tabel tabel-borderless" style="margin: 0 auto">
                    <tr>
                        <td style="vertical-align: center;">
                            Items per page {{Form::select('r',['15'=>'15','30'=>'30','45'=>'45','60'=>'60','75'=>'75','90'=>'90'], (isset($_GET['r']) ? $_GET['r'] : '15'),['class'=>'form-control form-control-sm d-inline ml-2 mr-2','style'=>'width:60px;','id'=>'r'])}}  {{ $professions->firstItem() }} - {{ $professions->lastItem() }} of {{ $professions->total() }}
                        </td>
                        <td>
                            {{ $professions->appends(request()->except('page'))->links() }}
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
@endsection

@section('extra-js')

    <script>
        $(document).ready(function() {
            $('#status_filter').on('change', function() {
                this.form.submit();
            });
        });
    </script>

@endsection

resources/views/admin/profession/show.blade.php
@extends('admin.adminlte.default')

@section('title') Edit Master Data Profession @endsection

@section('header')
    <div class="container-fluid container-title">
        <h3>@yield('title')</h3>
        <div class="btn-toolbar float-right">
                <a href="{{route('admin.profession.index')}}" class="btn btn-dark float-right"><i class="fa fa-caret-left"></i> Back</a>
                <a href="{{route('admin.profession.edit', $profession)}}" class="btn btn-success float-right ml-1">Edit</a>
        </div>
    </div>
@endsection

@section('content')
    <div class="container-fluid">
        <hr />
        <div class="table-responsive">
            <table class="table table-bordered table-sm">
                <tbody>
                <tr>
                    <th>Name:</th>
                    <td>
                        {{Form::text('name', $profession->name, ['class'=>'form-control form-control-sm'. ($errors->has('name') ? ' is-invalid' : ''), 'id' => 'name', 'disabled' => 'disabled'])}}
                        @foreach($errors->get('industry') as $error)
                            <div class="invalid-feedback">
                                {{$error}}
                            </div>
                        @endforeach
                    </td>
                </tr>
                <tr>
                    <th>Status:</th>
                    <td>
                        {{Form::select('status_id', $status_drop_down, $profession->status_id, ['class'=>'form-control form-control-sm ','id'=>'status_id', 'disabled' => 'disabled'])}}
                        @foreach($errors->get('status_id') as $error)
                            <div class="invalid-feedback">
                                {{$error}}
                            </div>
                        @endforeach
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
@endsection